[package]
name = "get-dir"
version = "0.1.0"
authors = ["chinanf-boy <865501259@qq.com>"]
edition = "2018"

[dependencies]
libc = "*"
rustc-serialize = "*"
error-chain= "*"

[lib]
crate-type = ["cdylib"]